CONTINUOUS_GENERATIONS = True
GENERATION_TIME = 1000

CHEAT_ANTI_EXTINCTION = True
ANTI_EXTINCTION_THRESHOLD = 5
ANTI_EXTINCTION_BONCE_BACK = 10
ANTI_EXTINCTION_BONCE_BACK_WITH_SURVIVOR=True

PLANT_SPAWN = True
PLANT_CYCLE = 30
PLANT_RATE = 1

