CONTINUOUS_GENERATIONS = True
GENERATION_TIME = 10000

START_CREATURE_COUNT = 200
START_PLANT_COUNT = 300

CHEAT_ANTI_EXTINCTION = False
ANTI_EXTINCTION_BOUNCE_TREE_TOO = True
ANTI_EXTINCTION_THRESHOLD = 5
ANTI_EXTINCTION_BONCE_BACK = START_CREATURE_COUNT
ANTI_EXTINCTION_BONCE_BACK_WITH_SURVIVOR=True

KICKSTART_MODE = True
KICKSTART_RESPAWN_PERCENT = 0.1

PLANT_SPAWN = True
PLANT_CYCLE = 30
PLANT_RATE = 3

DAMPENING = 0.2